version: 2
multi-ecosystem-groups:
  weekly-maintenance:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: pip
    directory: /
    multi-ecosystem-group: weekly-maintenance

  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: weekly-maintenance
